from django.conf.urls import patterns, include, url
from django.contrib import admin

urlpatterns = patterns('',
    url(r'^$', 'wishableapp.views.home', name='home'),
    url(r'^login$', 'django.contrib.auth.views.login', 
    	{'template_name':'login.html'}, name='login'),
    url(r'^register$', 'wishableapp.views.register', name='register'),
    url(r'^confirm-registration/(?P<username>[a-zA-Z0-9_@\+\-]+)/(?P<token>[a-z0-9\-]+)$', 
        'wishableapp.views.confirm_registration', name='confirm'),
    url(r'^logout$', 'django.contrib.auth.views.logout_then_login', name='logout'),
    url(r'^wishing-well$', 'wishableapp.views.wishing_well', name='wishing-well'),
    # url(r'^profile/(?P<username>.+)$', 'wishableapp.views.profile', name='profile'),
    # url(r'^profile$', 'wishableapp.views.profile', name='profile'),
    url(r'^profile/(?P<username>\w+)$', 'wishableapp.views.profile', name='profile'),
    # url(r'^webscrape-demo$', 'wishableapp.views.webscrape_demo', name='demo'),
    url(r'^catalog/(?P<prodtype>\w+)$', 'wishableapp.views.catalog', name='catalog'),
    url(r'^photo/(?P<id>\d+)$', 'wishableapp.views.get_photo', name='photo'),
    # url(r'^add-to-wishlist/(?P<prod_id>\d+)/(?P<wishlist_id>\d+)$', 'wishableapp.views.add_to_wishlist', name='add-to-wishlist'),
    url(r'^add-to-wishlist/$', 'wishableapp.views.add_to_wishlist', name='add-to-wishlist'),
    url(r'^scrape-product/$', 'wishableapp.views.scrape_product', name='scrape-product'),
    url(r'^add-new-product/$', 'wishableapp.views.add_new_product', name='add-new-product'),
    url(r'^product-photo/(?P<id>\d+)$', 'wishableapp.views.get_product_photo', name='product-photo'),
    url(r'^wishlist/(?P<wishlist_id>\d+)$', 'wishableapp.views.wishlist', name='wishlist'),
    url(r'^delete-wishlist-item/$', 'wishableapp.views.delete_wishlist_item', name='delete-wishlist-item'),
    url(r'^follow/(?P<username>\w+)$', 'wishableapp.views.follow', name='follow'),
    url(r'^unfollow/(?P<username>\w+)$', 'wishableapp.views.unfollow', name='unfollow'),
    url(r'^delete-wishlist/$', 'wishableapp.views.delete_wishlist', name='delete-wishlist'),
    url(r'^wishlist-item/(?P<wId>\d+)$', 'wishableapp.views.wishlist_item', name="wishlist-item"),
    url(r'^product/(?P<pId>\d+)$', 'wishableapp.views.product', name="product"),
    url(r'^edit-profile/(?P<username>\w+)$', 'wishableapp.views.editProfile', name="editProfile"),
    url(r'^add-pre-companies/(?P<companyID>\d+)$', 'wishableapp.views.addPrefCompanies', name="addPrefCompanies"),
    url(r'^remove-pre-companies/(?P<companyID>\d+)$', 'wishableapp.views.removePrefCompanies', name="removePrefCompanies"),
    url(r'^fairyGodMother/(?P<wItemId>\d+)$', 'wishableapp.views.fairyGodMother', name="fairyGodMother"),
    url(r'^editWishList/(?P<wishListId>\d+)$', 'wishableapp.views.editWishList', name="editWishList"),
)
